version: "3"

services:
  task-service:
    build: 
      context: .
      dockerfile: ./EduPlatform.UserService/Dockerfile
    command: 
      - bash
      - -c
      - sleep 50000
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      ./.env
    ports:
      - "8081:8081"
      - "8080:8080"
  
  postgres:
    image: postgres
    restart: always
    env_file:
      ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5